# Configuration for Node in App Engine standard on Google Cloud Platform.

runtime: nodejs8
instance_class: F1

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
